import { StyleSheet } from 'react-native';
 
const HomeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#6C2BD9',
    paddingTop: 12,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 16,
    marginBottom: 16,
  },
  menuIcon: {
    fontSize: 24,
    color: '#fff',
  },
  headerRight: {
    flexDirection: 'row',
    gap: 16,
    alignItems: 'center',
  },
  notificationIcon: {
    fontSize: 20,
    color: '#fff',
  },
  profileIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFD700',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 16,
  },
  cardContainer: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  card: {
    backgroundColor: '#1a1a1a',
    borderRadius: 16,
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  cardLeft: {
    flex: 1,
  },
  balanceLabel: {
    fontSize: 12,
    color: '#999',
    marginBottom: 8,
    fontWeight: '600',
  },
  balanceAmount: {
    fontSize: 16,
    color: '#fff',
    fontWeight: 'bold',
    letterSpacing: 2,
    marginBottom: 4,
  },
  payoLabel: {
    fontSize: 11,
    color: '#FFD700',
    fontWeight: '600',
  },
  cardRight: {
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    minWidth: 120,
  },
  walletDecoration: {
    width: 80,
    height: 60,
    backgroundColor: '#FFD700',
    borderRadius: 12,
    opacity: 0.8,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#333',
  },
  walletLabel: {
    fontSize: 12,
    color: '#999',
    fontWeight: '600',
  },
  walletButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  walletButtonText: {
    fontSize: 13,
    color: '#fff',
    fontWeight: '600',
  },
  walletArrow: {
    fontSize: 18,
    color: '#FFD700',
  },
  actionsContainer: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  actions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    gap: 16,
  },
  actionButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FFD700',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  actionIcon: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000',
  },
  actionLabel: {
    fontSize: 11,
    color: '#fff',
    marginTop: 6,
    fontWeight: '600',
    textAlign: 'center',
  },
  actionWrapper: {
    alignItems: 'center',
    flex: 1,
  },
  statsContainer: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  statsCard: {
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  statItem: {
    alignItems: 'center',
    flex: 1,
  },
  statIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  statValue: {
    fontSize: 14,
    color: '#fff',
    fontWeight: 'bold',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 11,
    color: '#999',
    fontWeight: '600',
  },
  divider: {
    width: 1,
    backgroundColor: '#333',
    marginHorizontal: 16,
  },
  transactionsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    marginBottom: 16,
  },
  transactionsTitle: {
    fontSize: 16,
    color: '#fff',
    fontWeight: 'bold',
  },
  viewAllText: {
    fontSize: 12,
    color: '#FFD700',
    fontWeight: '600',
  },
  transactionsList: {
    paddingHorizontal: 24,
    marginBottom: 100,
  },
  transactionItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  transactionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  transactionAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 18,
  },
  transactionInfo: {
    flex: 1,
  },
  transactionName: {
    fontSize: 13,
    color: '#fff',
    fontWeight: '600',
    marginBottom: 4,
  },
  transactionTime: {
    fontSize: 11,
    color: '#999',
  },
  transactionAmount: {
    fontSize: 13,
    fontWeight: 'bold',
  },
  amountPositive: {
    color: '#10B981',
  },
  amountNegative: {
    color: '#EF4444',
  },
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#1a1a1a',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 12,
    paddingBottom: 20,
    borderTopWidth: 1,
    borderTopColor: '#333',
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  navIcon: {
    fontSize: 24,
    marginBottom: 4,
  },
  navLabel: {
    fontSize: 10,
    color: '#999',
    fontWeight: '600',
  },
  navActive: {
    color: '#FFD700',
  },
  navInactive: {
    color: '#666',
  },
  centerIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#6C2BD9',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -24,
    shadowColor: '#6C2BD9',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
});
 
export default HomeStyles;
 